"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express = require("express");
var bodyParser = require("body-parser");
var rooms_router_1 = require("./rooms-router");
var tracks_router_1 = require("./tracks-router");
var auth_router_1 = require("./auth-router");
exports.app = express();
exports.app.use(bodyParser.json());
exports.app.use('/rooms', rooms_router_1.router);
exports.app.use('/tracks', tracks_router_1.router);
exports.app.use('/auth', auth_router_1.router);
